### PR TITLE
Adding wpcom-shortcodes.php file

### PR DESCRIPTION
**Pull request by emrikol**
Starting this file with a basic "protected embeds" wrapper.  It's not "protected" but it will at least output the embed code :)

### CODE REVIEW

**Review by alexiskulash — APPROVED** [review]
Looks good to me! Renders embeds during testing 👍

**Review by alexiskulash — APPROVED** [review]
Thanks for adding the filters! I tested `wpcom_protected_embed_html` and it works as expected, resolving the HTTP -> HTTPS issue on a client site.

**Comment by emrikol** [comment]
I think one other thing I'd like to test before I merge this is to check and make sure it doesn't override an already existing `protected-iframe` shortcode if it exists.  Or at least check through any current sites for ones that are using that shortcode and make sure it doesn't break anything for them.

**Comment by emrikol** [comment]
I did some basic testing with this shortcode running on a site that had https://github.com/humanmade/protected-embeds installed and I didn't see any issues.  I'm going to go ahead and merge it in.

**Pull request merged**
