### PR TITLE
Add deprecated functions from WPCOM

### PR DESCRIPTION
**Pull request by emrikol**
This adds `wpcom_vip_load_wp_rest_api()` as a deprecated function.  This is likely present in some themes, and will fatal on VIP Go since it's a WPCOM specific function.

### CODE REVIEW

**Comment by mjangda** [comment]
Should we create a new `deprecated.php` file?

**Comment by emrikol** [comment]
> Should we create a new deprecated.php file?

That's a good question.  Is it worth it for the single deprecated function right now?  I'm happy to move it to a separate file if you think it's better.

**Comment by mjangda** [comment]
Let's move it with the assumption that there will be more :)

**Comment by emrikol** [comment]
Done! :)

**Review by mjangda — APPROVED** [review]

**Pull request merged**
